# Generated by Django 4.0.3 on 2022-05-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_servicing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_comp', models.CharField(choices=[('M', 'Movement'), ('S', 'Strap'), ('C', 'Crystal')], default='G', max_length=1)),
                ('subtype_comp', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='servicing',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='servicing',
            name='date',
            field=models.DateField(verbose_name='Servicing Date'),
        ),
    ]
