# Generated by Django 4.0.3 on 2022-05-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_watch_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='subtype_comp',
            field=models.CharField(choices=[('MQ', 'Quartz'), ('MA', 'Automatic'), ('MM', 'Manual'), ('SL', 'Leather'), ('SM', 'Metal'), ('CA', 'Acrylic'), ('CM', 'Mineral'), ('CS', 'Sapphire')], max_length=2),
        ),
    ]
